CREATE TABLE IF NOT EXISTS partition_a (
	GUID VARCHAR(36) COLLATE "C" NOT NULL,
	ACTUAL BOOLEAN NOT NULL DEFAULT TRUE,
	NAME VARCHAR(1000),
	CONSTRAINT PK_partition_a_GUID PRIMARY KEY (GUID, ACTUAL)
) PARTITION BY LIST (ACTUAL);

CREATE TABLE IF NOT EXISTS partition_a_ACTUAL
PARTITION OF partition_a FOR VALUES IN (TRUE);

CREATE TABLE IF NOT EXISTS partition_a_NOT_ACTUAL
PARTITION OF partition_a FOR VALUES IN (FALSE);

CREATE TABLE IF NOT EXISTS partition_b (
	GUID VARCHAR(36) COLLATE "C" NOT NULL,
	ACTUAL BOOLEAN NOT NULL DEFAULT TRUE,
	NAME VARCHAR(1000),
	P_GUID VARCHAR(36),
	P_ACTUAL BOOLEAN,
	CONSTRAINT PK_partition_b_GUID PRIMARY KEY (GUID, ACTUAL),
	CONSTRAINT FK_partition_b FOREIGN KEY (P_GUID, P_ACTUAL) REFERENCES partition_a(GUID, ACTUAL)
) PARTITION BY LIST (ACTUAL);

CREATE TABLE IF NOT EXISTS partition_b_ACTUAL
PARTITION OF partition_b FOR VALUES IN (TRUE);

CREATE TABLE IF NOT EXISTS partition_b_NOT_ACTUAL
PARTITION OF partition_b FOR VALUES IN (FALSE);



